### PR TITLE
updating bio info

### PR DESCRIPTION
**Pull request by shanicetbailey**
shanice
I also changed the .jpg file name because I'd like to upload a different profile picture but I don't have access to do so. So I just dragged the picture to this comment box. Hopefully you're able to add the profile on your end - if not, I'd be happy to email it. Thanks!

### CODE REVIEW

**Comment by rabernat** [comment]
Hi Shanice! Thanks for this update.

In order to get your photo into the website, you need to add the file to the branch from which you made your pull request (PR). When you edited the text on github, a branch called `patch-1` was automatically created on your fork (https://github.com/stb2145/group-website/tree/patch-1). You can use github to add the new file in the `_static/photos` directory: https://github.com/stb2145/group-website/tree/patch-1/_static/photos

Once you make a new commit there, this PR will automatically update.

**Comment by rabernat** [comment]
p.s Great photo! 📸

**Comment by shanicetbailey** [comment]
Thanks! Ok, I uploaded the photo via https://github.com/stb2145/group-website/tree/patch-1/_static/photos. It says my branch is `2 commits ahead, 1 commit behind ocean-transport:master`.

**Comment by rabernat** [comment]
Perfect!

**Pull request merged**
