### PR TITLE
Add Paige to postdocs

### PR DESCRIPTION
**Pull request by paigem**

### CODE REVIEW

**Comment by paigem** [comment]
Still need to add my photo - what's the best way to do this? @rabernat

**Comment by paigem** [comment]
Also, I currently have my Michigan email listed. Will change to Lamont address if I can get one!

**Comment by rabernat** [comment]
> Still need to add my photo - what's the best way to do this?

See what @jbusecke did over in #10.

**Comment by jbusecke** [comment]
You have to force add the photo once you fork the top and make a new branch. `git add -f filename` otherwise git just ignores it.

**Comment by paigem** [comment]
Superseded by #11

**Pull request closed without merging**
